In [3]:
from tensorly.base import unfold, fold
import numpy as np
import tensorly.backend as T

## Readme

I can't intergate matlab to jupyter so i counted task 1 and task 7 in matlab separately (i added the *.m file to Canvas). There is only description to 7 number.

## 1.

Computed in __first_task.m__

## 2.

$\circ$  - outer product

$ A = a \circ  b = \textbf{a} \cdot \textbf{b}^T $

$A \otimes  B = vec(\textbf{a} \cdot \textbf{b}^T) = vec (a \circ b)$

It means that vector that we have - a vectorized matrix, which has rank 1, because it is an outer product.
We should restore all possible matrix from vector (in our case it is 2*3 and 3*2 matrix size) and look at its' rank.
If any rank equals 1, the initial vector is a Kronecker product.

In [1]:
vector = [-0.0158, -0.9533, -0.3560, 0.0155, 0.9336, 0.3486]

In [3]:
from numpy import matrix, rank
A = matrix([[-0.0158, -0.9533],[-0.3560, 0.0155],[0.9336, 0.3486]])
print (rank(A))

2


/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  This is separate from the ipykernel package so we can avoid doing imports until


In [4]:
A = matrix([[-0.0158, -0.9533,-0.3560], [0.0155, 0.9336, 0.3486]])
print (rank(A))

2


/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  


check we can't tangle the row-column:

In [6]:
A = matrix([[-0.0158, -0.3560, 0.9336], [-0.9533, 0.0155, 0.3486]])
print (rank(A))

2


/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  


In [7]:
A = matrix([[-0.0158, -0.0155], [-0.9533, 0.9336],[-0.3560, 0.3486]])
print (rank(A))

2


/opt/.pyenv/versions/3.7.4/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  


It seems no...

## 3.

If matrix is a Kroneker product of matrices,

$ A = \textbf{b}^T \cdot \textbf{c}$

It looks like one comppnent of SVD decomposition:

$ A = \sum_i \sigma_i {u_i}^T v_i $

So, If it is possible to approximate matrix to 1-rank matrices SVD, it is a Kronecker product of matrices.

In [16]:
from scipy import linalg

a = matrix([[0.1377, -0.6071, -0.3400, -0.0335, -0.1475, 0.0826],[-0.2289, 0.0524, -0.4639, 0.0556, -0.0127, 0.1127],[-0.3498, -1.5757, -0.7783, 0.0850, 0.3827, 0.1890], [-0.2990, 1.3181, 0.7381, 0.0436, -0.1923, -0.1077], [0.4969, -0.1139, 1.0072, -0.0725, 0.0166, -0.1470],[0.7595, 3.4209, 1.6898, -0.1108, -0.4992, -0.2466]])

U, s, Vh = linalg.svd(a)

In [17]:
s

array([4.64539687, 1.18056707, 0.59816744, 0.24738481, 0.0871925 ,
       0.00813466])

In [18]:
from sklearn.utils.extmath import randomized_svd
randomized_svd(a, 1)

(array([[-0.13845822],
        [-0.04563238],
        [-0.39506433],
        [ 0.31411823],
        [ 0.09751928],
        [ 0.84527565]]),
 array([4.64539687]),
 array([[ 0.15630438,  0.86078866,  0.45941007, -0.02551136, -0.13151443,
         -0.07488217]]))

Possible, it is.

## 4.

Frobeniuos norm of Kruskal Tensor

$||Y||^F_2 = \textbf{1}^{T} (\{A^{T} A\} \circ \{B^{T} B\} \circ  \{C^{T} C\} ) \textbf{1}$

where $\circ$ - Hadamard product 

## 5.

$||X - Y||^F_2  = ||Y||^F_2 + ||X||^F_2 - 2 <Y, X> =$
$ = \textbf{1}^{T} (A^T A \cdot B^T B \cdot C^T C) \textbf{1} + \textbf{1}^{T} (U^T U \cdot V^T V \cdot W^T W) \textbf{1} + \textbf{1}^{T} (U^T A \cdot V^T B \cdot W^T C) \textbf{1}$

## 6.

ALS step update rule for Kruskal tensor

$Y_{1} = U\cdot(W⊙V)^T$

$Y_{1}^T = (W⊙V)\cdot U^{T}$

$(W⊙V)^{+}\cdot Y_{(1)}^{T} = U^{T}$

$Y_{(1)}\cdot((W⊙V)^{+})^{T} = U$

$Y_{(1)}\cdot((W^{T}W \circ V^{T}V)(W⊙V)^{T})^{T} = U$

$Y_{(1)}\cdot((W⊙V)^{T})^{T} = U$

$U = Y_{(1)}\cdot (W⊙V)$

## 7.


$T_{(3)}$ (three-term matricization of $T$) $= C*(B⊙A)^{T}$

$T_{(3)} = (B⊙A)\cdot C^{T}$

$(B⊙A)^{+} \cdot T_{(3)}^{T} = C^{T}$

$C = T_{(3)} \cdot ((B⊙A)^{T})^{+}$

Computed in __task7.m__

## 8

In some case yes, but:
1) we need to use another matricization term
2) there are some constraint

If factor matrix A is given:

$T_{(1)} = A(C⊙B)^{T}$

$A^{T}T_{(1)} = A^{T} A \cdot (C⊙B)^{T}$

If matrix A is not singular (__this is constraint__) => $A^{T} A = I$

So:
$A^{T} T_{(1)}$ = $(C⊙B)^{T}$

The left part is given, the second part is a cronecker product:

$(C⊙B)^{T} = [c_1⊗b_1, ..., c_r⊗b_r]$

If matrix in a left part is a Kronecker product of two vectors (see n2.) it means find two other factor matrices is possible.


In [ ]:
Generate tensor with rank 6